# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home', models.CharField(default='', max_length=30)),
                ('homeScore', models.IntegerField()),
                ('visitor', models.CharField(default='', max_length=30)),
                ('visitorScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=30)),
                ('date', models.DateField()),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
